// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgdxubmoffqnzxpszkyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZHh1Ym1vZmZxbnp4cHN6a3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTY1NTksImV4cCI6MjA3MjE5MjU1OX0.4rqY3yUU8jRRPr4XxOalt1Mkn4oKL8gMZI2ecPxnCPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});